// Demo data for fallback when API is unavailable
export const DEMO_JOBS = [

  // ─── ELECTRICAL (includes AC Technician) ────────────────────────────
  {
    _id: 'demo_el1',
    title: 'House Wiring Electrician',
    company: 'Spark Electric Works Kasaragod',
    location: 'Kasaragod, Kerala',
    pincode: '671121',
    salary: '₹700–₹900/day',
    jobType: 'Daily Wages',
    industry: 'Electrical',
    category: 'electrical',
    experience: '2-4 years',
    vacancies: 3,
    applicantCount: 1,
    description: 'Residential house wiring work including switchboard installation, cable laying, and DB panel fitting. Work hours: 8:00 AM – 5:00 PM. PPE provided. Payment daily on completion.',
    skills: ['Electrical Wiring', 'Switchboard Installation', 'Cable Laying'],
    startDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 12 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_el2',
    title: 'Solar Rooftop Installation Electrician',
    company: 'SunPower Kerala Pvt Ltd',
    location: 'Nileshwaram, Kasaragod',
    pincode: '671314',
    salary: '₹900–₹1,200/day',
    jobType: 'Daily Wages',
    industry: 'Electrical',
    category: 'electrical',
    experience: '2-4 years',
    vacancies: 4,
    applicantCount: 2,
    description: 'Solar panel installation on rooftops for residential and commercial clients across Kasaragod district. Work involves panel mounting, wiring, inverter setup, and earthing. Hours: 8 AM – 5 PM. Safety harness provided.',
    skills: ['Solar Wiring', 'Inverter Setup', 'Panel Mounting'],
    startDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 15 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_el3',
    title: 'AC Installation & Service Technician',
    company: 'CoolBreeze AC Services Kasaragod',
    location: 'Kasaragod, Kerala',
    pincode: '671121',
    salary: '₹800–₹1,100/day',
    jobType: 'Daily Wages',
    industry: 'Electrical',
    category: 'electrical',
    experience: '2-4 years',
    vacancies: 3,
    applicantCount: 1,
    description: 'Split AC installation, gas charging, service and repairs for residential and small commercial units. Work timings: 9 AM – 6 PM. Must have own basic tools. Transport allowance paid if travel required.',
    skills: ['AC Installation', 'Gas Charging', 'AC Service', 'Refrigeration Basics'],
    startDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 15 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_el4',
    title: 'Commercial HVAC Technician',
    company: 'Arctic Cool Systems Kanhangad',
    location: 'Kanhangad, Kasaragod',
    pincode: '671315',
    salary: '₹1,000–₹1,400/day',
    jobType: 'Daily Wages',
    industry: 'Electrical',
    category: 'electrical',
    experience: '4-6 years',
    vacancies: 2,
    applicantCount: 0,
    description: 'Installation and AMC servicing of centralized AC systems, VRF units, and cassette ACs for commercial buildings. Work hours: 8:30 AM to 5:30 PM. Must have experience in ductwork and HVAC wiring.',
    skills: ['HVAC', 'VRF Systems', 'Ductwork', 'Centralized AC'],
    startDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 20 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },

  // ─── PLUMBING ────────────────────────────────────────────────────────
  {
    _id: 'demo_pl1',
    title: 'Residential Plumber',
    company: 'AquaFix Plumbing Services',
    location: 'Cheruvathur, Kasaragod',
    pincode: '671313',
    salary: '₹650–₹850/day',
    jobType: 'Daily Wages',
    industry: 'Plumbing',
    category: 'plumbing',
    experience: '2-4 years',
    vacancies: 2,
    applicantCount: 1,
    description: 'New residential plumbing work — water supply lines, drainage fitting, bathroom fixture installation, and overhead tank connections. Work timing: 8:00 AM to 5:00 PM. All pipe materials supplied.',
    skills: ['Plumbing', 'Pipe Fitting', 'Drainage Fitting'],
    startDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 14 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_pl2',
    title: 'Apartment Complex Plumber',
    company: 'Kerala Homes Builders',
    location: 'Kanjangad, Kasaragod',
    pincode: '671322',
    salary: '₹750–₹950/day',
    jobType: 'Daily Wages',
    industry: 'Plumbing',
    category: 'plumbing',
    experience: '4-6 years',
    vacancies: 3,
    applicantCount: 1,
    description: 'Multi-floor apartment plumbing work including hot and cold water lines, PVC drainage stacks, sanitary fixture installation, and RCC slab pipe embedment. Work hours: 8 AM to 5 PM. Safety shoes required.',
    skills: ['Plumbing', 'Hot & Cold Lines', 'Bathroom Fitting', 'Drainage Stacks'],
    startDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 20 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_pl3',
    title: 'Plumbing Maintenance Worker',
    company: 'SwiftFix Services Kasaragod',
    location: 'Kasaragod, Kerala',
    pincode: '671121',
    salary: '₹600–₹750/day',
    jobType: 'Daily Wages',
    industry: 'Plumbing',
    category: 'plumbing',
    experience: '1-2 years',
    vacancies: 2,
    applicantCount: 0,
    description: 'Plumbing maintenance and repair work for residential buildings — leak detection, tap replacement, pipe repair, tank cleaning, and drainage unblocking. Timing 8 AM onwards. Tools provided.',
    skills: ['Plumbing', 'Leak Repair', 'Tank Cleaning'],
    startDate: new Date(Date.now() + 1 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 10 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },

  // ─── FARMING ─────────────────────────────────────────────────────────
  {
    _id: 'demo_fa1',
    title: 'Coconut Plantation Farm Workers',
    company: 'Nair Coconut Farm Hosdurg',
    location: 'Hosdurg, Kasaragod',
    pincode: '671348',
    salary: '₹500–₹650/day',
    jobType: 'Daily Wages',
    industry: 'Farming',
    category: 'farming',
    experience: '1-2 years',
    vacancies: 8,
    applicantCount: 3,
    description: 'Seasonal farm labour for coconut and arecanut plantation — weeding, irrigation maintenance, harvesting, and coconut tree climbing. Work timing: 7:30 AM to 1:00 PM. Lunch provided. Group hiring open — bring your team.',
    skills: ['Coconut Harvesting', 'Tree Climbing', 'Weeding', 'Irrigation'],
    startDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 20 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: true,
    maxGroupSize: 8,
  },
  {
    _id: 'demo_fa2',
    title: 'Paddy Field Workers – Transplanting Season',
    company: 'EcoGrow Organic Farms Kasaragod',
    location: 'Kumbla, Kasaragod',
    pincode: '671321',
    salary: '₹550–₹700/day',
    jobType: 'Daily Wages',
    industry: 'Farming',
    category: 'farming',
    experience: 'Less than 1 year',
    vacancies: 10,
    applicantCount: 4,
    description: 'Paddy transplanting, weeding, and maintenance work for the upcoming Kharif season. Group workers welcome. Work hours: 7:00 AM to 12:30 PM. Meals provided. Daily payment. Female workers also welcome.',
    skills: ['Paddy Cultivation', 'Transplanting', 'Weeding', 'Field Work'],
    startDate: new Date(Date.now() + 6 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 25 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: true,
    maxGroupSize: 10,
  },
  {
    _id: 'demo_fa3',
    title: 'Vegetable Farm Labour – Year Round',
    company: 'Fresh Greens Agro Kasaragod',
    location: 'Nileshwaram, Kasaragod',
    pincode: '671314',
    salary: '₹500–₹600/day',
    jobType: 'Daily Wages',
    industry: 'Farming',
    category: 'farming',
    experience: 'Fresher',
    vacancies: 5,
    applicantCount: 2,
    description: 'Daily agricultural work on a vegetable farm — seed sowing, watering, fertilizing, pest control, and harvest. Timing: 7 AM to 1 PM. 6 days a week. Accommodation available for outstation workers.',
    skills: ['Vegetable Farming', 'Irrigation', 'Harvesting', 'Seed Sowing'],
    startDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 30 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: true,
    maxGroupSize: 5,
  },

  // ─── CONSTRUCTION ────────────────────────────────────────────────────
  {
    _id: 'demo_con1',
    title: 'Mason / Bricklayer – Residential Project',
    company: 'Kasaragod Builders Co.',
    location: 'Kasaragod, Kerala',
    pincode: '671121',
    salary: '₹700–₹900/day',
    jobType: 'Daily Wages',
    industry: 'Construction',
    category: 'construction',
    experience: '2-4 years',
    vacancies: 6,
    applicantCount: 2,
    description: 'Experienced masons needed for a 3-storey residential building. Work includes brick laying, plastering, and column construction. Work hours: 8 AM – 5 PM. PPE provided. Group hiring welcomed for this project.',
    skills: ['Masonry', 'Plastering', 'Bricklaying', 'Column Work'],
    startDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 18 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: true,
    maxGroupSize: 6,
  },
  {
    _id: 'demo_con2',
    title: 'Construction Site Labour – Foundation Work',
    company: 'Buildzone Infratech Kasaragod',
    location: 'Kanjangad, Kasaragod',
    pincode: '671322',
    salary: '₹600–₹750/day',
    jobType: 'Daily Wages',
    industry: 'Construction',
    category: 'construction',
    experience: '1-2 years',
    vacancies: 12,
    applicantCount: 4,
    description: 'General construction labour for foundation and structure work — digging, concrete mixing, material carrying, and shuttering support. Group applications encouraged. Work hours: 7:30 AM – 5:30 PM. Site meals available.',
    skills: ['Concreting', 'Manual Labour', 'Shuttering', 'Digging'],
    startDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 20 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: true,
    maxGroupSize: 12,
  },
  {
    _id: 'demo_con3',
    title: 'Steel Fixer / Bar Bender',
    company: 'Concretto Constructions Kasaragod',
    location: 'Kanhangad, Kasaragod',
    pincode: '671124',
    salary: '₹800–₹1,050/day',
    jobType: 'Daily Wages',
    industry: 'Construction',
    category: 'construction',
    experience: '2-4 years',
    vacancies: 5,
    applicantCount: 2,
    description: 'Steel fixing and bar bending work for multi-storey commercial building. Involves cutting, bending and tying rebars for columns, beams and slabs. Work timing: 8 AM – 5 PM. Safety equipment and PPE provided on site.',
    skills: ['Steel Fixing', 'Bar Bending', 'Rebar Tying'],
    startDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 22 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: true,
    maxGroupSize: 5,
  },
  {
    _id: 'demo_con4',
    title: 'Carpenter – Shuttering & Formwork',
    company: 'NovaBuild Infrastructure Kasaragod',
    location: 'Kasaragod, Kerala',
    pincode: '671316',
    salary: '₹750–₹950/day',
    jobType: 'Daily Wages',
    industry: 'Construction',
    category: 'construction',
    experience: '4-6 years',
    vacancies: 4,
    applicantCount: 1,
    description: 'Shuttering carpentry for RCC slabs, columns and beams in a large residential project. Must have experience with shuttering plywood, props, and timbering. Work from 8 AM. Group applications accepted.',
    skills: ['Shuttering', 'Formwork', 'Carpentry', 'Concreting Support'],
    startDate: new Date(Date.now() + 6 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 25 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: true,
    maxGroupSize: 4,
  },

  // ─── EVENT MANAGEMENT (includes Catering) ────────────────────────────
  {
    _id: 'demo_ev1',
    title: 'Wedding Catering Helper',
    company: 'Grand Kerala Caterers',
    location: 'Kasaragod, Kerala',
    pincode: '671121',
    salary: '₹600–₹800/day',
    jobType: 'Daily Wages',
    industry: 'Catering',
    category: 'event_management',
    experience: 'Less than 1 year',
    vacancies: 6,
    applicantCount: 2,
    description: 'Event catering assistance for wedding functions — food serving, dish washing, vessel cleaning, setup and breakdown. Work timing varies: typically 6 AM to 3 PM or 12 PM to 10 PM based on event. Food and uniform provided.',
    skills: ['Food Serving', 'Catering', 'Event Setup', 'Dish Washing'],
    startDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 15 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_ev2',
    title: 'Outside Catering – Event Cook',
    company: 'Zaika Catering Services Kanhangad',
    location: 'Kanhangad, Kasaragod',
    pincode: '671315',
    salary: '₹700–₹1,000/day',
    jobType: 'Daily Wages',
    industry: 'Catering',
    category: 'event_management',
    experience: '2-4 years',
    vacancies: 4,
    applicantCount: 1,
    description: 'Cook required for outside catering events — weddings, birthday parties, office events. Must be skilled in Kerala-style biriyani, sadya, and non-veg preparations. Events mostly on weekends. Transport arranged.',
    skills: ['Kerala Cuisine', 'Biriyani', 'Sadya', 'Event Cooking'],
    startDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 25 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_ev3',
    title: 'Hotel Kitchen Helper / Cook Assistant',
    company: 'Malabar Heritage Hotel Kasaragod',
    location: 'Kasaragod, Kerala',
    pincode: '671121',
    salary: '₹550–₹700/day',
    jobType: 'Daily Wages',
    industry: 'Catering',
    category: 'event_management',
    experience: '1-2 years',
    vacancies: 3,
    applicantCount: 1,
    description: 'Kitchen helper role in a hotel — cutting, washing, preparation, and assisting the head cook. Morning shift: 6 AM – 2 PM / Evening shift: 2 PM – 10 PM. Uniform and meals included. Kerala cuisine knowledge preferred.',
    skills: ['Kitchen Work', 'Food Preparation', 'Cooking Assistance'],
    startDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 20 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },

  // ─── LOCAL WORKERS (includes Labourers & Salesman) ───────────────────
  {
    _id: 'demo_lw1',
    title: 'Warehouse Loading / Unloading Labour',
    company: 'Malabar Logistics Hub Kasaragod',
    location: 'Kasaragod, Kerala',
    pincode: '671121',
    salary: '₹500–₹650/day',
    jobType: 'Daily Wages',
    industry: 'Logistics',
    category: 'local_workers',
    experience: 'Fresher',
    vacancies: 8,
    applicantCount: 3,
    description: 'Loading and unloading of goods in a logistics warehouse. Work involves handling bags, boxes, and pallets. Shift timings: 7 AM – 3 PM and 3 PM – 11 PM. Physical fitness required. Daily payment.',
    skills: ['Loading / Unloading', 'Warehouse Work', 'Manual Labour'],
    startDate: new Date(Date.now() + 1 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 12 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_lw2',
    title: 'Road Work / Municipal Labour',
    company: 'Kasaragod Infrastructure Works',
    location: 'Nileshwaram, Kasaragod',
    pincode: '671314',
    salary: '₹550–₹680/day',
    jobType: 'Daily Wages',
    industry: 'Infrastructure',
    category: 'local_workers',
    experience: '1-2 years',
    vacancies: 10,
    applicantCount: 5,
    description: 'General labour for road laying, footpath construction, and gutter work under municipal project. Work hours: 7:30 AM – 4:30 PM, 6 days a week. Tools and PPE provided. Daily wages paid on site.',
    skills: ['Road Work', 'Manual Labour', 'Digging', 'Paving'],
    startDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 16 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_lw3',
    title: 'Tile Laying / Flooring Helper',
    company: 'FloorCraft Interiors Kasaragod',
    location: 'Kasaragod, Kerala',
    pincode: '671318',
    salary: '₹600–₹750/day',
    jobType: 'Daily Wages',
    industry: 'Construction',
    category: 'local_workers',
    experience: '1-2 years',
    vacancies: 4,
    applicantCount: 1,
    description: 'Tile fixing and flooring helper for residential and commercial projects. Involves mixing adhesive, tile cutting, grouting, and surface cleaning. Work timing: 8 AM to 5 PM. Training provided for semi-skilled workers.',
    skills: ['Tiling', 'Grouting', 'Tile Cutting', 'Surface Preparation'],
    startDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 15 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },

  // ─── OTHER (includes Salesman) ────────────────────────────────────────
  {
    _id: 'demo_ot1',
    title: 'Field Sales Executive – Building Materials',
    company: 'Kasaragod Hardware & Tiles',
    location: 'Kasaragod, Kerala',
    pincode: '671121',
    salary: '₹14,000–₹20,000/month + Incentives',
    jobType: 'Full-time',
    industry: 'Sales',
    category: 'other',
    experience: '1-2 years',
    vacancies: 3,
    applicantCount: 2,
    description: 'Visit retail shops and construction sites to sell tiles, sanitary ware, and building materials. Target-based incentives. Work timings: Monday to Saturday, 9 AM – 6 PM. Two-wheeler required (fuel allowance provided).',
    skills: ['Field Sales', 'Customer Relations', 'Product Knowledge'],
    startDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 25 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_ot2',
    title: 'Retail Sales Associate – Electronics',
    company: 'Malabar Electronics Kanhangad',
    location: 'Kanhangad, Kasaragod',
    pincode: '671315',
    salary: '₹12,000–₹18,000/month',
    jobType: 'Full-time',
    industry: 'Sales',
    category: 'other',
    experience: 'Less than 1 year',
    vacancies: 2,
    applicantCount: 3,
    description: 'Counter sales in an electronics showroom — assist customers in choosing products, billing, and after-sales service follow-up. Timing: 9:30 AM – 8:00 PM, Sunday holiday. Training provided for freshers.',
    skills: ['Retail Sales', 'Customer Service', 'Billing'],
    startDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 30 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
  {
    _id: 'demo_ot3',
    title: 'Medical Representative – Pharma Sales',
    company: 'MedLink Pharma Kerala',
    location: 'Kasaragod, Kerala',
    pincode: '671316',
    salary: '₹18,000–₹28,000/month + TA/DA',
    jobType: 'Full-time',
    industry: 'Sales',
    category: 'other',
    experience: '2-4 years',
    vacancies: 2,
    applicantCount: 1,
    description: 'Cover doctors, clinics, and pharmacies in Kasaragod and Kanhangad areas for pharmaceutical product promotion. Monday–Saturday, 9 AM–6 PM. Two-wheeler required. Science graduate preferred.',
    skills: ['Pharma Sales', 'Doctor Visits', 'Product Detailing'],
    startDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    deadline: new Date(Date.now() + 35 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    status: 'active',
    allowGroupApply: false,
    adminApproved: true,
  },
];

export const DEMO_WORKERS = [
  // Electrical (including AC technicians)
  { _id: 'w_el1', name: 'Anwar Hussain', location: 'Kasaragod - 671319', pincode: '671319', experience: '2-4 years', skills: ['Electrical Wiring', 'Panel Installation', 'Cable Laying'], languages: ['Malayalam', 'Hindi'], about: 'Licensed electrician available for residential and commercial wiring work.', workCategory: 'electrical', availability: 'Immediate', rating: 4.7 },
  { _id: 'w_el2', name: 'Jobin George', location: 'Kasaragod - 671122', pincode: '671122', experience: '4-6 years', skills: ['Solar Wiring', 'Inverter Setup', 'Panel Installation'], languages: ['Malayalam', 'English'], about: 'Solar electrician experienced in rooftop installations across Kasaragod.', workCategory: 'electrical', availability: 'Immediate', rating: 4.9 },
  { _id: 'w_el3', name: 'Vinod Babu', location: 'Kasaragod - 671121', pincode: '671121', experience: '4-6 years', skills: ['Electrical Wiring', 'Switchboard Installation', 'DB Panel'], languages: ['Malayalam', 'Tamil'], about: 'Certified electrician with 5 years in apartment and commercial wiring projects.', workCategory: 'electrical', availability: 'Immediate', rating: 4.8 },
  { _id: 'w_el4', name: 'Nishad Kunhi', location: 'Kasaragod - 671121', pincode: '671121', experience: '2-4 years', skills: ['AC Installation', 'Gas Charging', 'AC Service', 'Refrigeration'], languages: ['Malayalam', 'Hindi'], about: 'AC technician trained in split and window ACs. Available for installation and service.', workCategory: 'electrical', availability: 'Immediate', rating: 4.6 },
  { _id: 'w_el5', name: 'Sreekanth P', location: 'Kasaragod - 671315', pincode: '671315', experience: '4-6 years', skills: ['HVAC', 'VRF Systems', 'Ductwork', 'Centralized AC'], languages: ['Malayalam', 'English'], about: 'HVAC technician with 5 years in commercial AC systems and VRF installations.', workCategory: 'electrical', availability: 'Within 1 week', rating: 4.8 },
  // Plumbing
  { _id: 'w_pl1', name: 'Biju Thomas', location: 'Kasaragod - 671312', pincode: '671312', experience: '6-10 years', skills: ['Plumbing', 'Pipe Fitting', 'Leak Repair'], languages: ['Malayalam', 'English'], about: 'Expert plumber with 8 years of experience in residential and commercial projects.', workCategory: 'plumbing', availability: 'Immediate', rating: 4.9 },
  { _id: 'w_pl2', name: 'Arjun Shetty', location: 'Kasaragod - 671313', pincode: '671313', experience: '2-4 years', skills: ['Plumbing', 'Drainage Fitting', 'Water Supply Lines'], languages: ['Malayalam', 'Tulu'], about: 'Plumber experienced in new construction plumbing — drainage, water lines, and bathroom fixtures.', workCategory: 'plumbing', availability: 'Immediate', rating: 4.5 },
  { _id: 'w_pl3', name: 'Sunil Varghese', location: 'Kasaragod - 671317', pincode: '671317', experience: '4-6 years', skills: ['Plumbing', 'Hot & Cold Lines', 'Bathroom Fitting'], languages: ['Malayalam', 'English'], about: 'Certified plumber skilled in luxury bathroom fitting and full plumbing solutions.', workCategory: 'plumbing', availability: 'Within 1 week', rating: 4.6 },
  { _id: 'w_pl4', name: 'Rithesh Nambiar', location: 'Kasaragod - 671318', pincode: '671318', experience: '2-4 years', skills: ['Plumbing', 'GI Pipes', 'Tank Cleaning'], languages: ['Malayalam'], about: 'Plumber with experience in apartments and commercial complexes.', workCategory: 'plumbing', availability: 'Immediate', rating: 4.4 },
  // Farming
  { _id: 'w_fa1', name: 'Selin Joseph', location: 'Kasaragod - 671531', pincode: '671531', experience: '2-4 years', skills: ['Paddy Cultivation', 'Crop Harvesting', 'Irrigation Management'], languages: ['Malayalam', 'English'], about: 'Seasonal farm worker experienced in paddy and coconut farming in Kasaragod.', workCategory: 'farming', availability: 'Immediate', rating: 4.5 },
  { _id: 'w_fa2', name: 'Suresh Kumar', location: 'Kasaragod - 671532', pincode: '671532', experience: '4-6 years', skills: ['Coconut Climbing', 'Fruit Picking', 'Crop Harvesting'], languages: ['Malayalam', 'Tamil'], about: 'Skilled coconut tree climber and agricultural worker.', workCategory: 'farming', availability: 'Within 1 week', rating: 4.6 },
  { _id: 'w_fa3', name: 'Lijin Mathews', location: 'Kasaragod - 671533', pincode: '671533', experience: '4-6 years', skills: ['Organic Farming', 'Seed Sowing', 'Pesticide Application'], languages: ['Malayalam'], about: 'Organic farmer with experience in spice and vegetable cultivation.', workCategory: 'farming', availability: 'Immediate', rating: 4.6 },
  { _id: 'w_fa4', name: 'Murugesan S', location: 'Kasaragod - 671541', pincode: '671541', experience: '2-4 years', skills: ['Vegetable Farming', 'Irrigation', 'Transplanting'], languages: ['Malayalam', 'Tamil'], about: 'Farm worker experienced in paddy transplanting and vegetable cultivation.', workCategory: 'farming', availability: 'Immediate', rating: 4.3 },
  // Construction
  { _id: 'w_con1', name: 'Rajan Pillai', location: 'Kasaragod - 671321', pincode: '671321', experience: '4-6 years', skills: ['Masonry', 'Plastering', 'Bricklaying'], languages: ['Malayalam', 'Tamil'], about: 'Experienced mason with 5 years in residential and commercial construction.', workCategory: 'construction', availability: 'Immediate', rating: 4.8 },
  { _id: 'w_con2', name: 'Shiva Kumar', location: 'Kasaragod - 671314', pincode: '671314', experience: '2-4 years', skills: ['Concreting', 'Shuttering', 'Manual Labour'], languages: ['Malayalam', 'Hindi'], about: 'Construction worker with experience in residential and commercial projects.', workCategory: 'construction', availability: 'Immediate', rating: 4.4 },
  { _id: 'w_con3', name: 'Deepak Nair', location: 'Kasaragod - 671315', pincode: '671315', experience: '6-10 years', skills: ['Carpentry', 'Shuttering', 'Formwork'], languages: ['Malayalam', 'English'], about: 'Skilled shuttering carpenter for RCC construction projects.', workCategory: 'construction', availability: 'Within 1 week', rating: 4.9 },
  { _id: 'w_con4', name: 'Prakashan K', location: 'Kasaragod - 671324', pincode: '671324', experience: '6-10 years', skills: ['Steel Fixing', 'Bar Bending', 'Welding'], languages: ['Malayalam'], about: 'Structural steel fixer with a decade of experience in building projects.', workCategory: 'construction', availability: 'Within 1 week', rating: 4.8 },
  // Event Management (catering workers)
  { _id: 'w_ev1', name: 'Meena Devi', location: 'Kasaragod - 671542', pincode: '671542', experience: '1-2 years', skills: ['Food Serving', 'Catering', 'Event Setup'], languages: ['Malayalam', 'Tamil'], about: 'Catering helper for events and weddings. Experienced in food serving and kitchen assistance.', workCategory: 'event_management', availability: 'Immediate', rating: 4.3 },
  { _id: 'w_ev2', name: 'Roshan K', location: 'Kasaragod - 671121', pincode: '671121', experience: '2-4 years', skills: ['Kerala Cuisine', 'Biriyani', 'Sadya', 'Event Cooking'], languages: ['Malayalam'], about: 'Experienced event cook specializing in Kerala-style wedding food preparations.', workCategory: 'event_management', availability: 'Immediate', rating: 4.7 },
  { _id: 'w_ev3', name: 'Abhilash P R', location: 'Kasaragod - 671543', pincode: '671543', experience: '2-4 years', skills: ['Sound Systems', 'Lighting', 'Stage Setup'], languages: ['Malayalam', 'English'], about: 'Event technician with experience in sound and lighting for weddings and corporate events.', workCategory: 'event_management', availability: 'Immediate', rating: 4.7 },
  // Local Workers (labourers)
  { _id: 'w_lw1', name: 'Kiran Mohan', location: 'Kasaragod - 671552', pincode: '671552', experience: 'Fresher', skills: ['Warehouse Work', 'Loading / Unloading', 'Sorting'], languages: ['Malayalam'], about: 'Hardworking warehouse labourer, punctual and available for immediate deployment.', workCategory: 'local_workers', availability: 'Immediate', rating: 4.2 },
  { _id: 'w_lw2', name: 'Dinesh Raj', location: 'Kasaragod - 671348', pincode: '671348', experience: '1-2 years', skills: ['Manual Labour', 'Road Work', 'Digging'], languages: ['Malayalam', 'Tamil'], about: 'General labourer with experience in road construction and site clearing.', workCategory: 'local_workers', availability: 'Immediate', rating: 4.1 },
  { _id: 'w_lw3', name: 'Arun Babu', location: 'Kasaragod - 671322', pincode: '671322', experience: '1-2 years', skills: ['Tiling Helper', 'Grouting', 'Floor Work'], languages: ['Malayalam', 'Tamil'], about: 'Flooring helper for tile laying and surface preparation work.', workCategory: 'local_workers', availability: 'Immediate', rating: 4.4 },
  // Other (salesman)
  { _id: 'w_ot1', name: 'Aslam K', location: 'Kasaragod - 671351', pincode: '671351', experience: '2-4 years', skills: ['Field Sales', 'Customer Relations', 'Product Demonstration'], languages: ['Malayalam', 'Hindi'], about: 'Sales executive with experience in hardware and building materials distribution.', workCategory: 'other', availability: 'Immediate', rating: 4.4 },
  { _id: 'w_ot2', name: 'Priya Nair', location: 'Kasaragod - 671326', pincode: '671326', experience: '1-2 years', skills: ['Retail Sales', 'Customer Service', 'Billing'], languages: ['Malayalam', 'English'], about: 'Counter sales associate with experience in electronics and FMCG retail.', workCategory: 'other', availability: 'Immediate', rating: 4.5 },
];

export const DEMO_EMPLOYERS = [
  { _id: 'e1', name: 'Kasaragod Builders Co.', location: 'Kasaragod, Kerala', industry: 'Construction', activeJobs: 4 },
  { _id: 'e2', name: 'Nair Coconut Farm', location: 'Hosdurg, Kasaragod', industry: 'Farming', activeJobs: 2 },
  { _id: 'e3', name: 'Spark Electric Works', location: 'Kasaragod, Kerala', industry: 'Electrical', activeJobs: 3 },
  { _id: 'e4', name: 'AquaFix Plumbing Services', location: 'Cheruvathur, Kasaragod', industry: 'Plumbing', activeJobs: 3 },
  { _id: 'e5', name: 'Grand Kerala Caterers', location: 'Kasaragod, Kerala', industry: 'Events / Catering', activeJobs: 2 },
  { _id: 'e6', name: 'CoolBreeze AC Services', location: 'Kasaragod, Kerala', industry: 'Electrical / AC', activeJobs: 2 },
  { _id: 'e7', name: 'Buildzone Infratech', location: 'Kanjangad, Kasaragod', industry: 'Construction', activeJobs: 5 },
  { _id: 'e8', name: 'EcoGrow Organic Farms', location: 'Hosdurg, Kasaragod', industry: 'Farming', activeJobs: 3 },
  { _id: 'e9', name: 'SunPower Kerala Pvt Ltd', location: 'Kanhangad, Kasaragod', industry: 'Electrical / Solar', activeJobs: 3 },
  { _id: 'e10', name: 'Malabar Logistics Hub', location: 'Kasaragod, Kerala', industry: 'Logistics', activeJobs: 2 },
  { _id: 'e11', name: 'Zaika Catering Services', location: 'Kanhangad, Kasaragod', industry: 'Events / Catering', activeJobs: 3 },
  { _id: 'e12', name: 'Kasaragod Hardware & Tiles', location: 'Kasaragod, Kerala', industry: 'Sales', activeJobs: 2 },
  { _id: 'e13', name: 'Malabar Electronics', location: 'Kanhangad, Kasaragod', industry: 'Sales / Electronics', activeJobs: 2 },
  { _id: 'e14', name: 'Concretto Constructions', location: 'Kanhangad, Kasaragod', industry: 'Construction', activeJobs: 3 },
  { _id: 'e15', name: 'Arctic Cool Systems', location: 'Kanhangad, Kasaragod', industry: 'Electrical / AC', activeJobs: 2 },
  { _id: 'e16', name: 'Fresh Greens Agro', location: 'Nileshwaram, Kasaragod', industry: 'Farming', activeJobs: 2 },
  { _id: 'e17', name: 'FloorCraft Interiors', location: 'Kasaragod, Kerala', industry: 'Construction', activeJobs: 2 },
  { _id: 'e18', name: 'Malabar Heritage Hotel', location: 'Kasaragod, Kerala', industry: 'Events / Catering', activeJobs: 2 },
  { _id: 'e19', name: 'Kerala Homes Builders', location: 'Kanjangad, Kasaragod', industry: 'Construction', activeJobs: 3 },
  { _id: 'e20', name: 'MedLink Pharma Kerala', location: 'Kasaragod, Kerala', industry: 'Sales', activeJobs: 2 },
];
